import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import sys
import os

def load_cp_distribution(filename):
    """
    Load Cp distribution from the file generated by computeCpDistribution().
    Format: x y x_over_c Cp side
    """
    data = []
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith('#'):
                continue
            parts = line.split()
            if len(parts) < 5:
                continue
            try:
                xc = float(parts[2])   # x/c
                cp = float(parts[3])   # Cp
                side = parts[4]        # 'U' or 'L'
                if not np.isfinite(cp):
                    continue
                data.append((xc, cp, side))
            except ValueError:
                continue
    if not data:
        return np.array([]), np.array([]), np.array([])
    xc_vals = np.array([d[0] for d in data])
    cp_vals = np.array([d[1] for d in data])
    side_vals = np.array([d[2] for d in data])
    return xc_vals, cp_vals, side_vals

def main():
    if len(sys.argv) < 2:
        print("Usage: python Cp.py <cp_distribution.dat> [output_image.png]")
        print("Example: python Cp.py results/naca0012_cp_distribution.dat")
        sys.exit(1)

    input_file = sys.argv[1]
    if len(sys.argv) >= 3:
        output_file = sys.argv[2]
    else:
        base, _ = os.path.splitext(input_file)
        output_file = base + '.png'

    xc, cp, side = load_cp_distribution(input_file)
    if len(xc) == 0:
        print(f"No valid data found in {input_file}")
        return

    # Separate upper (U) and lower (L) surfaces
    upper_mask = side == 'U'
    lower_mask = side == 'L'

    xc_upper = xc[upper_mask]
    cp_upper = cp[upper_mask]
    xc_lower = xc[lower_mask]
    cp_lower = cp[lower_mask]

    # Sort by x/c for clean lines
    idx_upper = np.argsort(xc_upper)
    idx_lower = np.argsort(xc_lower)

    plt.figure(figsize=(10, 6))
    plt.plot(xc_upper[idx_upper], cp_upper[idx_upper], 'b.-', label='Upper surface')
    plt.plot(xc_lower[idx_lower], cp_lower[idx_lower], 'r.-', label='Lower surface')

    plt.xlabel('x/c')
    plt.ylabel('C_p')
    plt.title('Pressure Coefficient Distribution (NACA0012, M=0.8)')
    plt.legend()
    plt.grid(True)
    plt.gca().invert_yaxis()   # typical aerodynamic plot
    plt.tight_layout()

    plt.savefig(output_file, dpi=300)
    print(f"Plot saved to {output_file}")
    plt.close()

if __name__ == '__main__':
    main()